name: Build APK Direct

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install Gradle
      run: |
        sudo apt update
        sudo apt install -y gradle
        
    - name: Build with Gradle
      run: gradle assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: direct-apk
        path: app/build/outputs/apk/debug/app-debug.apk
