name: Build from Scratch

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Initialize Gradle project
      run: |
        # Создаем базовую структуру Gradle
        gradle init --type basic --dsl groovy --project-name "MultsParser"
        
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: scratch-apk
        path: app/build/outputs/apk/debug/app-debug.apk
