name: Build Simple Fix

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Simple fix and build
      run: |
        # Простое исправление line endings
        tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: simple-fix-apk
        path: app/build/outputs/apk/debug/app-debug.apk
