name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK Debug
      run: ./gradlew assembleDebug
      
    - name: Build APK Release
      run: |
        ./gradlew assembleRelease
        ls -la app/build/outputs/apk/release/
      
    - name: Upload APK Debug
      uses: actions/upload-artifact@v4
      with:
        name: mults-parser-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
        
    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: mults-parser-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 7
        
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/release/app-release.apk
          app/build/outputs/apk/debug/app-debug.apk
        body: |
          🎬 Mults Parser - Android APK
          
          ### Что нового:
          - Парсинг каталога mults.info
          - Простой интерфейс
          - Открытие в браузере
          
          ### Установка:
          1. Скачайте APK файл
          2. Разрешите установку из неизвестных источников
          3. Установите приложение
